services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: coach
    container_name: postgres
    volumes:
      - ~/coach-postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: always
