name: 🚀 Deploy to EC2 with PM2

on:
    push:
        branches:
            - main  # ou "master" selon ton repo

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup SSH
              run: |
                  mkdir -p ~/.ssh
                  echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa
                  ssh-keyscan -H 13.38.238.211 >> ~/.ssh/known_hosts

            - name: Deploy via SSH
              run: |
                  ssh ubuntu@13.38.238.211 << 'EOF'
                    cd /mentori-app
                    git pull origin main
                    npm ci
                    npm run build:server
                    pm2 restart api
                  EOF
