name: Deploy React to S3

on:
    push:
        branches: [main]  # ou [production] si besoin

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install dependencies
              run: npm install

            - name: Build React app
              run: npm run build --workspace=app
              env:
                  REACT_APP_SERVER_URL: ${{ secrets.REACT_APP_SERVER_URL }}

            - name: Sync to S3
              uses: jakejarvis/s3-sync-action@master
              with:
                  args: --delete
              env:
                  AWS_S3_BUCKET:
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  AWS_REGION: eu-west-3
                  SOURCE_DIR: dist/app
